name 'base_image'
maintainer 'Allen Madsen'
maintainer_email 'blatyo@gmail.com'
license 'All rights reserved'
description 'Installs/Configures base_image'
long_description 'Installs/Configures base_image'
version '0.1.0'
